import type { Metadata } from "next";
import { Nunito, Mohave } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });
const mohave = Mohave({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sam Baldwin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mohave.className}>{children}</body>
    </html>
  );
}
